# HerpAI-Ingestion Configuration

app:
  name: "HerpAI-Ingestion"
  log_level: "INFO"

database:
  host: "localhost"
  port: 5432
  database: "herpai"
  username: "postgres"
  password: "postgres"
  dialect: "postgresql"
  driver: "asyncpg"
  pool_size: 5
  max_overflow: 10
  schema: "public"

storage:
  type: "azure"  # Options: s3, nfs, azure
  azure:
    account_name: ""
    account_key: ""
    container_name: "herpai-datalake"
    prefix: "documents/"
  s3:
    bucket: "herpai-datalake"
    prefix: "documents/"
    region: "us-east-1"
    access_key: ""  # Leave empty to use IAM role or environment variables
    secret_key: ""
  nfs:
    mount_point: "/mnt/data"
    path: "documents/"

rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  vhost: "/"
  exchange: "herpai"
  queue_prefix: "herpai_ingestion_"
  routing_key_prefix: "herpai.ingestion."
  retry:
    max_attempts: 5
    initial_interval: 1.0  # seconds
    max_interval: 60.0     # seconds
    multiplier: 2.0

grobid:
  host: "localhost"
